In [1]:
import pandas as pd#引入pandas套件
trainDf = pd.read_csv("train.csv")#讀取訓練資料
trainDf.head(10)#先印出前十筆資料看一下有哪些feature

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [2]:
x_train_len=len(trainDf)#計算訓練資料的筆數
y_train = trainDf.iloc[:,-1]#拿出訓練資料的target
testDf = pd.read_csv("test.csv")#讀取測試資料
all_data = pd.concat([trainDf.iloc[:,1:-1],testDf.iloc[:,1:]])#合併訓練及測試資料的feature
all_data = pd.get_dummies(all_data)#對類別資料做one hot encoding
for i in range(len(all_data.iloc[0])):
    all_data.iloc[:,i] = all_data.iloc[:,i].fillna(all_data.iloc[:,i].median())#將空值補上那個欄位的中位數
all_data.head(10)#印出前十筆資料

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0
5,50,85.0,14115,5,5,1993,1995,0.0,732.0,0.0,...,0,0,0,1,0,0,0,0,1,0
6,20,75.0,10084,8,5,2004,2005,186.0,1369.0,0.0,...,0,0,0,1,0,0,0,0,1,0
7,60,68.0,10382,7,6,1973,1973,240.0,859.0,32.0,...,0,0,0,1,0,0,0,0,1,0
8,50,51.0,6120,7,5,1931,1950,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
9,190,50.0,7420,5,6,1939,1950,0.0,851.0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [3]:
from sklearn.preprocessing import StandardScaler#引入標準化用的函式
standardScaler = StandardScaler()#生成標準化用的物件
standardScaler.fit(all_data)#訓練標準化用的模型
all_data = standardScaler.transform(all_data)#用訓練好的標準化模型轉換原本的資料
all_data[:5]#印出前五筆資料

array([[ 0.06733141, -0.19181473, -0.21787869, ..., -0.12653513,
         0.46393674, -0.30269297],
       [-0.87361603,  0.51193993, -0.07204408, ..., -0.12653513,
         0.46393674, -0.30269297],
       [ 0.06733141, -0.0510638 ,  0.13719688, ..., -0.12653513,
         0.46393674, -0.30269297],
       [ 0.30256828, -0.42639962, -0.07838472, ..., -0.12653513,
        -2.15546626, -0.30269297],
       [ 0.06733141,  0.69960783,  0.51890312, ..., -0.12653513,
         0.46393674, -0.30269297]])

In [4]:
x_train = all_data[:x_train_len,:]#從合併的資料拿出訓練資料
x_test = all_data[x_train_len:,:]#從合併的資料拿出測試資料

In [5]:
from xgboost import XGBRegressor#引入xgboost用的套件
from sklearn.model_selection import GridSearchCV#引入GridSearchCV用的套件
xgbRegressor =  XGBRegressor()
parameters = {'n_estimators':[200,300,400], 'max_depth':[3,4,5], 'reg_lambda':[0.1,0.2,0.3],'subsample':[0.7,0.8],'colsample_bytree':[0.7,0.8],'colsample_bylevel':[0.5,0.6,0.7,0.8]}#設定我要找的參數及範圍
gridSearchCV = GridSearchCV(xgbRegressor, parameters,cv=5)#將要訓練的模型及要找的參數和K-FOLD的數量給GridSearchCV
gridSearchCV.fit(x_train,y_train)#讓GridSearchCV用訓練資料找最佳參數
print(gridSearchCV.best_params_)#印出最佳參數確認一下

{'colsample_bylevel': 0.7, 'colsample_bytree': 0.7, 'max_depth': 3, 'n_estimators': 400, 'reg_lambda': 0.1, 'subsample': 0.7}

In [6]:
xgbRegressor =  XGBRegressor(**(gridSearchCV.best_params_))#將最佳參數傳進xgbRegressor
xgbRegressor.fit(x_train,y_train)#訓練xgbRegressor

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.7,
       colsample_bytree=0.7, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=400,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=0.1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.7)

In [7]:
testSalePrice = xgbRegressor.predict(x_test)#用訓練好之模型預測測試資料的target
testId = testDf['Id']
submission = pd.DataFrame({'Id':testId,'SalePrice':testSalePrice})#用DataFrame儲存結果以便輸出
submission.to_csv("result.csv",index = False)#將DataFrame內容輸出至csv